name: lens-conversion
channels:
  - conda-forge
dependencies:
  - awscli
  - bokeh
  - dask
  - dask-jobqueue
  - dask-labextension
  - distributed
  - intake
  - intake-esm>=2020.8.15
  - ipywidgets
  - ipywidgets
  - jupyterlab
  - matplotlib
  - nc-time-axis
  - netcdf4
  - nodejs
  - numpy
  - pip
  - python=3.8
  - s3fs
  - tqdm
  - watermark
  - xarray
  - zarr
  - pip:
       - ncar-jobqueue
