name: lens-conversion
channels:
  - conda-forge
dependencies:
  - awscli
  - bokeh==1.4.0
  - dask
  - dask-jobqueue
  - distributed
  - intake
  - intake-esm
  - ipywidgets
  - jupyterlab
  - netcdf4
  - nodejs
  - numpy
  - dask-labextension
  - ipywidgets
  - pip
  - python=3.8
  - s3fs
  - tqdm
  - watermark
  - xarray
  - zarr
  - pip:
       - ncar-jobqueue
