name: lens
channels:
  - conda-forge
dependencies:
  - python=3.6
  - jupyterlab
  - watermark
  - xarray
  - intake
  - intake-xarray
  - zarr
  - dask
  - distributed
  - numpy
  - pip
  - pip:
    - git+https://github.com/andersy005/intake-esm.git

