name: lens-conversion
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyterlab
  - watermark
  - xarray
  - intake
  - zarr
  - dask
  - distributed
  - numpy
  - pip
  - intake-esm==2020.3.16.1
