scenarios: 
   - hist
   - rcp85
frequencies: 
   - day
biascorrections: 
   - raw
variables:
   - tasmax
   - tasmin
   # Completed variables
grid_categories:
   high_res: 
      grid: NAM-22i
      chunks:
         time: 20
         lat: 5
         lon: 5
         member_id: 4
   low_res:
      grid: NAM-44i
      chunks:
         time: 20
         lat: 3
         lon: 3
         member_id: 4          