frequency: day
grid: NAM-22i
biascorrection: raw
variable_category:
   2D:
     variable:
       - tasmax
       # Completed Variables 
     scenario:
       rcp85:
         chunks:
           time: 200
           lat: -1
           lon: -1

#   3D:
#     variable:
#       - tasmax
#       # Completed Variables 
#     scenario:
#       rcp85:
#         chunks:
#           time: 200
#           lat: -1
#           lon: -1
#           z: -1

