scenarios: 
   - hist
   #- rcp85
frequencies: 
   - day
biascorrections: 
   - raw
variables:
   - tasmax
   #- tasmin
   #- pr
   #- prec
   #- prhmax
   #- ps
   #- rsds
   #- tas
   #- temp
   #- tmax
   #- tmin
   #- uas
   #- vas
   #- huss
   # Completed variables
   # PROBLEM VARIABLES
   #- hurs
   #- sfcWind
grid_categories:
   high_res: 
      grid: NAM-22i
      chunks:
         time: 1000
         lat: 65
         lon: 120


#   low_res:
#      grid: NAM-44i
#      chunks:
#         time: 20
#         lat: 3
#         lon: 3
#         member_id: 4          

target_metadata:
   keep_first:
      - CORDEX_domain
      - experiment
      - experiment_id
      - driving_experiment_name
      - frequency
      - id
      - project_id
      - product
   keep_all:
      - contact
      - creation_date
      - driving_model_id
      - driving_model_ensemble_member
      - driving_experiment
      - institution
      - institute_id
      - model_id
      - rcm_version_id
      - references
      - tracking_id
      - title
      - version
      
        