atm:
  cam.h0:
    frequency: monthly
    stream: cam.h0
    freq: MS
    time_bounds_dim: nbnd
    variable_category:
      3D:
        variable:
          - T
          - U
          - v
          - Q
          - Z3
        experiment:
          CTRL:
            chunks:
              time: 18

          RCP85:
            chunks:
              time: 18

          20C:
            chunks:
              time: 18

      2D:
        variable:
          - FLNS
          - FLNSC
          - FLUT
          - FSNS
          - FSNSC
          - FSNTOA
          - ICEFRAC
          - LHFLX
          - PRECC
          - PRECL
          - PRECSC
          - PRECSL
          - PSL
          - SHFLX
          - TMQ
          - TREFHT
          - TREFHTMN
          - TREFHTMX
          - TS

        experiment:
          CTRL:
            chunks:
              time: 576

          RCP85:
            chunks:
              time: 576

          20C:
            chunks:
              time: 576

  cam.h1:
    frequency: daily
    stream: cam.h1
    freq: D
    time_bounds_dim: nbnd
    variable_category:
      3D:
        variable:
          - T
          - U
          - v
          - Q
          - Z3
        experiment:
          CTRL:
            chunks:
              time: 18

          RCP85:
            chunks:
              time: 18

          20C:
            chunks:
              time: 18

      2D:
        variable:
          - FLNS
          - FLNSC
          - FLUT
          - FSNS
          - FSNSC
          - FSNTOA
          - ICEFRAC
          - LHFLX
          - PRECC
          - PRECL
          - PRECSC
          - PRECSL
          - PSL
          - SHFLX
          - TMQ
          - TREFHT
          - TREFHTMN
          - TREFHTMX
          - TS

        experiment:
          CTRL:
            chunks:
              time: 576

          RCP85:
            chunks:
              time: 576

          20C:
            chunks:
              time: 576

  cam.h2:
    frequency: hourly6
    stream: cam.h2
    freq: 6H
    time_bounds_dim: nbnd
    variable_category:
      2D:
        variable:
          - FLNS
          - FLNSC
          - FLUT
          - FSNS
          - FSNSC
          - FSNTOA
          - ICEFRAC
          - LHFLX
          - PRECC
          - PRECL
          - PRECSC
          - PRECSL
          - PSL
          - SHFLX
          - TMQ
          - TREFHT
          - TREFHTMN
          - TREFHTMX
          - TS

        experiment:
          CTRL:
            chunks:
              time: 576

          RCP85:
            chunks:
              time: 576

          20C:
            chunks:
              time: 576

      3D:
        variable:
          - T
          - U
          - v
          - Q
          - Z3
        experiment:
          CTRL:
            chunks:
              time: 20

          RCP85:
            chunks:
              time: 20

          20C:
            chunks:
              time: 20

lnd:
  clm2.h0:
    frequency: monthly
    stream: clm2.h0
    time_bounds_dim: hist_interval
    freq: MS
    variable_category:
      2D:
        variable:
          - FSNO
          - H2OSNO
          - QRUNOFF
          - RAIN
          - SNOW
          - SOILWATER_10CM
        experiment:
          CTRL:
            chunks:
              time: 600

          RCP85:
            chunks:
              time: 600

          20C:
            chunks:
              time: 600

      3D:
        variable:
          - SOILLIQ

        experiment:
          CTRL:
            chunks:
              time: 40

          RCP85:
            chunks:
              time: 40

          20C:
            chunks:
              time: 40

  clm2.h1:
    frequency: daily
    stream: clm2.h1
    time_bounds_dim: hist_interval
    freq: D
    variable_category:
      2D:
        variable:
          - FSNO
          - H2OSNO
          - QRUNOFF
          - RAIN
          - SNOW
          - SOILWATER_10CM
        experiment:
          CTRL:
            chunks:
              time: 600

          RCP85:
            chunks:
              time: 600

          20C:
            chunks:
              time: 600

      3D:
        variable:
          - SOILLIQ

        experiment:
          CTRL:
            chunks:
              time: 30

          RCP85:
            chunks:
              time: 30

          20C:
            chunks:
              time: 30
ice_sh:
  cice.h:
    frequency: monthly
    stream: cice.h
    freq: MS
    time_bounds_dim: d2
    variable_category:
      # 2D:
      #   variable:
      #     -
      #     -

      3D:
        variable:
          - hi
          - aice
        experiment:
          CTRL:
            chunks:
              time: 1224
              ni: 320
              nj: 104

          RCP85:
            chunks:
              time: -1
              ni: 320
              nj: 104

          20C:
            chunks:
              time: 1224
              ni: 320
              nj: 104

  cice.h1:
    frequency: daily
    stream: cice.h1
    freq: D
    time_bounds_dim: d2
    variable_category:
      # 2D:
      #   variable:
      #     -
      #     -
      3D:
        variable:
          - hi_d
          - aice_d

        experiment:
          CTRL:
            chunks:
              time: 1224
              ni: -1
              nj: -1

          RCP85:
            chunks:
              time: 1224
              ni: -1
              nj: -1

          20C:
            chunks:
              time: 1224
              ni: -1
              nj: -1
ice_nh:
  cice.h:
    frequency: monthly
    stream: cice.h
    freq: MS
    time_bounds_dim: d2
    variable_category:
      #      2D:
      #        variable:
      #          -
      #          -

      3D:
        variable:
          - hi
          - aice
        experiment:
          CTRL:
            chunks:
              time: 972
              ni: -1
              nj: -1

          RCP85:
            chunks:
              time: -1
              ni: -1
              nj: -1

          20C:
            chunks:
              time: 936
              ni: -1
              nj: -1

  cice.h1:
    frequency: daily
    stream: cice.h1
    freq: D
    time_bounds_dim: d2
    variable_category:
      # 2D:
      #   variable:
      #     -
      #     -
      3D:
        variable:
          - hi_d
          - aice_d

        experiment:
          CTRL:
            chunks:
              time: 108
              ni: -1
              nj: -1

          RCP85:
            chunks:
              time: 6000
              ni: -1
              nj: -1

          20C:
            chunks:
              time: 6000
              ni: -1
              nj: -1
ocn:
  pop.h:
    frequency: monthly
    stream: pop.h
    freq: MS
    time_bounds_dim: d2
    variable_category:
      2D:
        variable:
          # Completed Variables
          - SST
          - SSH
          - SFWF
          - SHF
          - TAUX
          - TAUY
          - FW
          - TAUX2
          - TAUY2
          - QFLUX
          - HMXL
          - QSW_HTP
          - QSW_HBL
          - SHF_QSW
          - SFWF_WRST
          - RESID_S
          #- RESID_T
        experiment:
          CTRL:
            chunks:
              time: 300
              nlat: -1
              nlon: -1
#               z_t: -1
#               z_w_top: -1
#               z_w_bot: -1
          20C:
            chunks:
              time: 300
              nlat: -1
              nlon: -1
#               z_t: -1
#               z_w_top: -1
#               z_w_bot: -1
          RCP85:
            chunks:
              time: 300
              nlat: -1
              nlon: -1
#               z_t: -1
#               z_w_top: -1
#               z_w_bot: -1

      3D:
        variable:
          # Completed Variables
          - SALT
          - TEMP
          - UVEL
          - VNS
          - VNT
          - VVEL
          - WVEL
          - UES
          - UET
          - DIC
          - DOC
          - PD
          - O2
          - WTS
          - WTT
        experiment:
          CTRL:
            chunks:
              time: 6
              nlat: -1
              nlon: -1
#               z_t: -1
#               z_w_top: -1
#               z_w_bot: -1
          20C:
            chunks:
              time: 6
              nlat: -1
              nlon: -1
#               z_t: -1
#               z_w_top: -1
#               z_w_bot: -1
          RCP85:
            chunks:
              time: 6
              nlat: -1
              nlon: -1
#               z_t: -1
#               z_w_top: -1
#               z_w_bot: -1
